function transform(data){

  //Array with expiration dates found in the different emails
  var compareDates = [
    {oldStr: /Ends ((?:January|February|March|April|May|June|July|August|September|October|November|December) \d{1,2})/i, newStr: "$1"},
    {oldStr: /through (.*), at 11:59pm PST/i, newStr: "$1"},
    {oldStr: /through 11:59PM ((?:\d{1,2}\/){2}\d{2,4})/i, newStr: "$1"},
    {oldStr: /made from (?:\d{1,2}\/){1,2}\d{2,4} through 11:59 pm PST on ((?:\d{1,2}\/){1,2}\d{2,4})/i, newStr: "$1"},
    {oldStr: /Valid from (?:\d{1,2}\/){2}\d{2,4} to ((?:\d{1,2}\/){2}\d{2,4})/i, newStr: "$1"},
  ];


  //Evaluate if there is an end date in the string coming from @alt
  var splitData = data.split("~~~");
  if(compareDates[0].oldStr.test(splitData[0])) return compareDates[0].oldStr.exec(data)[0].replace(compareDates[0].oldStr, compareDates[0].newStr);


  //split the second string depending on the matched keywords
  var matchKeywords = [
    /points/i
    /\*\*/,
    /\*/,
  ];

  for (var j = 0; j < matchKeywords.length; j++){
    if(splitData[0].search(matchKeywords[j]) !== -1) {
      splitData[1] = splitData[1].slice(splitData[1].search(matchKeywords[j]));
    return findDate(splitData[1], compareDates);
    }
  }


  return "";
}



function findDate(str, dates){
  for(var i = 0; i < dates.length; i++){
    var el = dates[i];
    if(el.oldStr.test(str)) return el.oldStr.exec(str)[0].replace(el.oldStr, el.newStr);
  }
}







var str = "Beauty INSIDER | IN STORE ONLY 3X BONUS POINTS | Earn points and redeem rewards | Get 3X points on your in-store beauty purchase now through Monday, December 25.*~~~*Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str1 = "While you're there, SCORE THE SCENTS OF THE SEASON | Get a free sample bag filled with nine fragrance favorites.** PRESENT OFFER *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str2 = "$24 ONLY AT SEPHORA. NEW. LIMITED EDITION. NARS - NARS x Man Ray: Love Triangle Blush/Lipstick Set ($34 value) > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str3 = "$25 NEW. LIMITED EDITION. LAURA MERCIER - Take a Powder Translucent Loose Setting Powder & Puff ($53 value) > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str4 = "$18.50 ONLY AT SEPHORA. NEW. LIMITED EDITION. CLINIQUE - Pep Your Pout ($29.50 value) > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str5 = "$25 BEAUTYBLENDER - Midas Touch ($28 value) > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str6 = "$24 ONLY AT SEPHORA INSIDE JCPENNEY. IN STORE ONLY. NEW. LIMITED EDITION. SEPHORA FAVORITES - Fragrance Sampler for Her ($44 value) > | Redeem enclosed voucher for a free rollerball(+) *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time."

str7 = "$24 NEW. LIMITED EDITION. PETER THOMAS ROTH - Cleanse. Drench. Repeat. ($33 value) > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.",

str8 = "Limited Quantities while supplies last | Weekly Wow - 50% off select beauty only(+) Grab new deals starting every Thursday at Sephora inside JCPenney. SHOP NOW > *Beauty Insiders will earn triple points on merchandise purchases from 12:01AM PT 12/18/17 through 11:59PM 12/25/17 in Sephora U.S. stores, Sephora Canada stores, Sephora inside JCPenney stores and on Sephora.com. Offer not valid on jcp.com. Bonus points will be automatically credited to your Beauty Insider account within 24 hours after purchase. No minimum purchase required. Non-transferable. Points not earned on previous purchases, purchases of gift cards or eGift cards, tax or shipping. This offer is subject to termination by Sephora at its sole discretion at any time. **Offer is available with any purchase at Sephora inside JCPenney stores only. Must be a registered Beauty Insider to redeem offer. Not available on sephora.com or in freestanding Sephora stores. Not valid at jcp.com. One per client, non-transferable. Valid from 12/19/17 to 1/19/17, or while supplies last; quantities are limited. Not valid on previous purchases or purchases of eGift certificates and gift cards. Barcode must be surrendered at time of redemption. Cannot be used in conjunction with other promotion codes. Sephora employees are not eligible for offer. No returns or exchanges. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time. †Markdowns available online and in stores from 12/14/2017-12/20/2017 on select products. Valid while supplies last; quantities are limited. Not valid on previous purchases. This offer is subject to change, alteration, or termination by Sephora at its sole discretion at any time.";



​
