function transform(data){
  var dataSpl = data.split("~~~");

  return /\$10\s*off/i.test(dataSpl[0]) && /\$10\s*off/i.test(dataSpl[1]) ?
  dataSpl[1].replace(/.*Valid\s*(?:January|February|March|April|May|June|July|August|September|October|November|December)\s*\d{1,2}–((?:January|February|March|April|May|June|July|August|September|October|November|December)\s*\d{1,2},?\s*\d{2,4}).*/i, "$1") :
  "";
}

var str = "$10 OFF ANYTHING*~~~About the $10 off: Valid March 21–April 21, 2019 in US stores and at dsw.com for $10 off a purchase of $10 or more. Use offer code 483332001004 to redeem online. Limit 1 per customer. One-time use. Not valid toward gift cards, past purchases, shipping, or tax. No cash back. Cannot be replaced if lost, stolen, or damaged. Value can be reused on same-day exchange only. Exclusions apply. See store or dsw.com for details. Additional details: May be combined with up to two Rewards and one offer. Excludes Birkenstock, Brooks, HUNTER, Keen, Koolaburra by UGG, Michael Michael Kors, Rainbow, Sorel, and UGG products, plus select Nike, New Balance, Converse, Steve Madden, and Under Armour styles. Excludes luggage and fragrance items. Not valid at any DSW Canada store or at www.dswcanada.ca. Associates of DSW and of other companies owned by Designer Brands are not eligible for offer. For help, contact shoephoria! Center: 1.866.DSW.SHOES or customerservice@dsw.com. About our prices:Advertised prices are available at dsw.com, but may not be available at all DSW stores. See store for details. Our COMP. VALUE prices typically refer to the manufacturer’s suggested retail price (MSRP). When an MSRP is not available, the COMP. VALUE price is our estimate of other retailers’ ticketed prices for the same or similar items."



"Earn 1 point for every $1 spent in purchases made by friends and family on dsw.com using the custom link you received via email. Points can only be earned by friends & family purchases; members cannot use their own custom link to earn additional points. Points are deposited monthly. Not valid towards gift cards, past purchases, shipping, or tax. Rewards points are not redeemable for cash and cannot be replaced if lost, stolen, or damaged. Exclusions apply. See store or ~~~About the $10 off: Valid March 21–April 21, 2019 in US stores and at dsw.com for $10 off a purchase of $10 or more. Use offer code 483332001004 to redeem online. Limit 1 per customer. One-time use. Not valid toward gift cards, past purchases, shipping, or tax. No cash back. Cannot be replaced if lost, stolen, or damaged. Value can be reused on same-day exchange only. Exclusions apply. See store or dsw.com for details. Additional details: May be combined with up to two Rewards and one offer. Excludes Birkenstock, Brooks, HUNTER, Keen, Koolaburra by UGG, Michael Michael Kors, Rainbow, Sorel, and UGG products, plus select Nike, New Balance, Converse, Steve Madden, and Under Armour styles. Excludes luggage and fragrance items. Not valid at any DSW Canada store or at www.dswcanada.ca. Associates of DSW and of other companies owned by Designer Brands are not eligible for offer. For help, contact shoephoria! Center: 1.866.DSW.SHOES or customerservice@dsw.com. About our prices:Advertised prices are available at dsw.com, but may not be available at all DSW stores. See store for details. Our COMP. VALUE prices typically refer to the manufacturer’s suggested retail price (MSRP). When an MSRP is not available, the COMP. VALUE price is our estimate of other retailers’ ticketed prices for the same or similar items.";
